import { Octokit } from "@octokit/rest";
import config from "../config.js";

const octokit = new Octokit({
  auth: config.github.token,
});

const OWNER = config.github.owner;
const REPO = config.github.repo;

export async function createPullRequest(branchName, summary) {
  const pr = await octokit.pulls.create({
    owner: OWNER,
    repo: REPO,
    title: `🤖 AI Repair: ${summary}`,
    head: branchName,
    base: "dev",
    body: `
## Automated AI Repair

This Pull Request was automatically generated.

### Summary

${summary}

---

Generated by BudgetCart AI Repair Agent.
`,
  });

  console.log("Pull Request Created:");
  console.log(pr.data.html_url);

  return pr.data.html_url;
}

export async function createIssue(title, body) {
  const issue = await octokit.issues.create({
    owner: OWNER,
    repo: REPO,
    title,
    body,
  });

  console.log("Issue Created:");
  console.log(issue.data.html_url);

  return issue.data.html_url;
}

export default {
  createPullRequest,
  createIssue,
};